#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPAbstractStructure.h"


@class SUPClassDelegate;
@class SUPClassMetaDataRBS;

// public interface declaration, can be used by application. 
/*!
 @class ODMobileKeyGeneratorPK
 @abstract This class is part of package "ODMobile:1.20"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/

@interface ODMobileKeyGeneratorPK : SUPAbstractStructure<SUPClassWithMetaData>
{
@private
    NSString* _remoteId;
    int64_t _batchId;
}

@property(retain,nonatomic) NSString* remoteId;
@property(assign,nonatomic) int64_t batchId;

- (id) init;
- (void)dealloc;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (ODMobileKeyGeneratorPK*)getInstance;
+ (SUPClassDelegate *)delegate;
+ (SUPClassMetaDataRBS*)metaData;
- (SUPClassMetaDataRBS*)getClassMetaData;


@end
typedef SUPObjectList ODMobileKeyGeneratorPKList;

// internal methods declaration, only used by generated code.
@interface ODMobileKeyGeneratorPK(internal)


- (SUPJsonObject*)getAttributeJson:(int)id_;
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value;

-(SUPLong) getAttributeLong:(int)id_;
-(void) setAttributeLong:(int)id_:(SUPLong)v;
-(SUPString) getAttributeString:(int)id_;
-(void) setAttributeString:(int)id_:(SUPString)v;
@end