#import "sybase_sup.h"
#import "SUPKeyGenerator.h"
#import "SUPKeyGeneratorPK.h"
#import "SUPClassWithMetaData.h"

@class SUPEntityMetaDataRBS;
@protocol SUPClassWithMetaData;
@class SUPEntityDelegate;
@class SUPClassMetaDataRBS;
@class ODMobileKeyGeneratorPK;

// public interface declaration, can be used by application.
/*!
 @class ODMobileKeyGenerator
 @abstract This class is part of package "ODMobile:1.21"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/

@interface ODMobileKeyGenerator : SUPKeyGenerator<SUPClassWithMetaData>
{
}
+ (SUPEntityDelegate *)delegate;
+ (SUPEntityMetaDataRBS*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (ODMobileKeyGenerator*)getInstance;
- (SUPClassMetaDataRBS*)getClassMetaData;
+ (int64_t) generateId;


@end