#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPAbstractEntityRBS.h"
#import "SUPMobileBusinessObject.h"
#import "SUPEntityDelegate.h"
#import "ODMobileMBO_getSubbranchesSynchronizationParameters.h"


@class SUPEntityMetaDataRBS;
@class SUPEntityDelegate;
@class SUPClassMetaDataRBS;
@class SUPQuery;

// public interface declaration, can be used by application. 
/*!
 @class ODMobileMBO_getSubbranches
 @abstract This class is part of package "ODMobile:1.20"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/

@interface ODMobileMBO_getSubbranches : SUPAbstractEntityRBS<SUPMobileBusinessObject, SUPClassWithMetaData>
{
@private
    NSString* _SUBBRANCH_ID;
    NSString* _SUBBRANCH_NAME;
    NSString* _CHIEF_EMPLOYEE_ID;
    NSString* _SUBBRANCH_LEVEL_ID;
    NSString* _ADDRESS;
    NSString* _LATITUDE;
    NSString* _LONGITUDE;
    NSString* _MVS_AREA_FLG;
    NSString* _ENABLED_FLG;
    NSString* _PARENT_ID;
    NSString* _OSB_ID;
    NSString* _GOSB_ID;
    NSString* _CA_ID;
    NSString* _TB_ID;
    int64_t _surrogateKey;
}

@property(retain,nonatomic) NSString* SUBBRANCH_ID;
@property(retain,nonatomic) NSString* SUBBRANCH_NAME;
@property(retain,nonatomic) NSString* CHIEF_EMPLOYEE_ID;
@property(retain,nonatomic) NSString* SUBBRANCH_LEVEL_ID;
@property(retain,nonatomic) NSString* ADDRESS;
@property(retain,nonatomic) NSString* LATITUDE;
@property(retain,nonatomic) NSString* LONGITUDE;
@property(retain,nonatomic) NSString* MVS_AREA_FLG;
@property(retain,nonatomic) NSString* ENABLED_FLG;
@property(retain,nonatomic) NSString* PARENT_ID;
@property(retain,nonatomic) NSString* OSB_ID;
@property(retain,nonatomic) NSString* GOSB_ID;
@property(retain,nonatomic) NSString* CA_ID;
@property(retain,nonatomic) NSString* TB_ID;
@property(assign,nonatomic) int64_t surrogateKey;

+ (SUPEntityMetaDataRBS*)metaData;
+ (SUPEntityDelegate *)delegate;
+ (void) registerCallbackHandler:(NSObject<SUPCallbackHandler>*)handler;
+ (NSObject<SUPCallbackHandler>*)callbackHandler;
- (SUPClassMetaDataRBS*)getClassMetaData;
/*!
  @method 
  @abstract Sets relationship attributes to null to save memory (they will be retrieved from the DB on the next getter call or property reference)
  @discussion
  @throws SUPPersistenceException
 */
- (void)clearRelationshipObjects;
- (id) init;
- (void)dealloc;
/*!
  @method 
  @abstract Returns the entity for the primary key value passed in, or null if the entity is not found.
  @discussion
  @throws SUPPersistenceException
 */
+ (ODMobileMBO_getSubbranches*)find:(int64_t)id_;
/*!
  @method 
  @abstract Returns an SUPObjectList of entity rows satisfying this query
  @discussion
  @throws SUPPersistenceException
 */
+ (SUPObjectList*)findWithQuery:(SUPQuery*)query;
/*!
  @method 
  @abstract Returns the primary key for this entity.
  @discussion
 */
- (int64_t)_pk;
/*!
  @method 
  @abstract Returns the entity for the primary key value passed in; throws an exception if the entity is not found.
  @discussion
  @throws SUPPersistenceException
 */
+ (ODMobileMBO_getSubbranches*)load:(int64_t)id;
/*!
  @method 
  @abstract Returns an SUPObjectList of log records for this entity.
  @discussion
  @throws SUPPersistenceException
 */
- (SUPObjectList*)getLogRecords;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (ODMobileMBO_getSubbranches*)getInstance;
/*!
  @method 
  @abstract Return a string description of this entity.
  @discussion
 */
- (NSString*)toString;
/*!
  @method 
  @abstract Return a string description of this entity.
  @discussion
 */
- (NSString*)description;
+ (void) submitPendingOperations;
+ (void) cancelPendingOperations;
- (SUPString)getLastOperation;
/*!
  @method 
  @abstract Return a list of ODMobileMBO_getSubbranches objects
  @discussion
  @throws SUPPersistenceException
 */
+ (SUPObjectList*)getPendingObjects;
/*!
  @method 
  @abstract Return a list of ODMobileMBO_getSubbranches objects
  @discussion
  @throws SUPPersistenceException
 */
+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @throws SUPPersistenceException
 */

+ (SUPObjectList*)findAll;

/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param skip
  @param take
  @throws SUPPersistenceException
 */

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param sUBBRANCH_ID
  @throws SUPPersistenceException
 */

+ (ODMobileMBO_getSubbranches*)findByPrimaryKey:(NSString*)sUBBRANCH_ID;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param parentId
  @throws SUPPersistenceException
 */

+ (SUPObjectList*)getByParentId:(NSString*)parentId;

/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param parentId
  @param skip
  @param take
  @throws SUPPersistenceException
 */

+ (SUPObjectList*)getByParentId:(NSString*)parentId skip:(int32_t)skip take:(int32_t)take;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @throws SUPPersistenceException
 */

+ (SUPQueryResultSet*)getRowsCount;

/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param skip
  @param take
  @throws SUPPersistenceException
 */

+ (SUPQueryResultSet*)getRowsCount:(int32_t)skip take:(int32_t)take;

/*!
  @method
  @abstract Generated class method 
  @throws SUPPersistenceException
 */
+ (ODMobileMBO_getSubbranchesSynchronizationParameters*)getSynchronizationParameters;
/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query;


@end
typedef SUPObjectList ODMobileMBO_getSubbranchesList;

// internal methods declaration, only used by generated code.
@interface ODMobileMBO_getSubbranches(internal)


- (SUPJsonObject*)getAttributeJson:(int)id_;
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value;

-(SUPLong) getAttributeLong:(int)id_;
-(void) setAttributeLong:(int)id_:(SUPLong)v;
-(SUPString) getAttributeNullableString:(int)id_;
-(void) setAttributeNullableString:(int)id_:(SUPString)v;
-(SUPString) getAttributeString:(int)id_;
-(void) setAttributeString:(int)id_:(SUPString)v;
@end