/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileMBOTaskTypesPriv.h"
#import "ODMobileMBOTaskTypesPrivMetaData.h"
#import "SUPJsonObject.h"
#import "ODMobileODMobileDB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "ODMobileKeyGenerator.h"
#import "ODMobileLocalKeyGenerator.h"
#import "ODMobileLogRecordImpl.h"
#import "SUPSyncParamEntityDelegate.h"

@implementation ODMobileMBOTaskTypesPriv

@synthesize TASK_TYPE_ID = _TASK_TYPE_ID;
@synthesize EMPLOYEE_ID = _EMPLOYEE_ID;
@synthesize surrogateKey = _surrogateKey;

- (int64_t)surrogateKey
{
    return _surrogateKey;
}

- (void)setTASK_TYPE_ID:(NSString*)newTASK_TYPE_ID
{
    if (newTASK_TYPE_ID != self->_TASK_TYPE_ID)
    {
		[self->_TASK_TYPE_ID release];
        self->_TASK_TYPE_ID = [newTASK_TYPE_ID retain];
        self.isDirty = YES;
    }
}

- (void)setEMPLOYEE_ID:(NSString*)newEMPLOYEE_ID
{
    if (newEMPLOYEE_ID != self->_EMPLOYEE_ID)
    {
		[self->_EMPLOYEE_ID release];
        self->_EMPLOYEE_ID = [newEMPLOYEE_ID retain];
        self.isDirty = YES;
    }
}

- (void)setSurrogateKey:(int64_t)newSurrogateKey
{
    if (newSurrogateKey != self->_surrogateKey)
    {
        self->_surrogateKey = newSurrogateKey;
        self.isNew = YES;
    }
}

static SUPEntityDelegate *g_ODMobileMBOTaskTypesPriv_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileMBOTaskTypesPriv_delegate == nil) {
			g_ODMobileMBOTaskTypesPriv_delegate = [[SUPEntityDelegate alloc] initWithName:@"ODMobileMBOTaskTypesPriv" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileMBOTaskTypesPriv_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* ODMobileMBOTaskTypesPriv_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (ODMobileMBOTaskTypesPriv_META_DATA == nil) {
		ODMobileMBOTaskTypesPriv_META_DATA = [[ODMobileMBOTaskTypesPrivMetaData alloc] init];
	}
	
	return ODMobileMBOTaskTypesPriv_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return [[self delegate] callbackHandler];
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	[[self delegate] registerCallbackHandler:newCallbackHandler];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [ODMobileMBOTaskTypesPriv metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[ODMobileMBOTaskTypesPriv delegate]];
    }
    return self;    
}

- (void)dealloc
{
    if(_TASK_TYPE_ID)
    {
        [_TASK_TYPE_ID release];
        _TASK_TYPE_ID = nil;
    }
    if(_EMPLOYEE_ID)
    {
        [_EMPLOYEE_ID release];
        _EMPLOYEE_ID = nil;
    }
	[super dealloc];
}


- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

+ (ODMobileMBOTaskTypesPriv*)find:(int64_t)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:[NSNumber numberWithLong:id_]];
    return (ODMobileMBOTaskTypesPriv*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

+ (SUPObjectList*)findWithQuery:(SUPQuery*)query
{
    return (SUPObjectList*)[(SUPEntityDelegate*)([[self class] delegate])  findWithQuery:query:[ODMobileMBOTaskTypesPriv class]];
}

- (int64_t)_pk
{
    return (int64_t)[[self i_pk] longValue];
}

+ (ODMobileMBOTaskTypesPriv*)load:(int64_t)id_
{
    return (ODMobileMBOTaskTypesPriv*)[(SUPEntityDelegate*)([[self class] delegate]) load:[NSNumber numberWithLong:id_]];
}

+ (ODMobileMBOTaskTypesPriv*)getInstance
{
    ODMobileMBOTaskTypesPriv* me = [[ODMobileMBOTaskTypesPriv alloc] init];
    [me autorelease];
    return me;
}
- (SUPString)getLastOperation
{
    if (self.pendingChange == 'C')
    {
        return @"create";
    }
    else if (self.pendingChange == 'D')
    {
        return @"delete";
    }
    else if (self.pendingChange == 'U')
    {
        return @"update";
    }
    return @"";

}
+ (void)submitPendingOperations
{
    [[[self class] delegate] submitPendingOperations];
}

+ (void)cancelPendingOperations
{
    [[[self class] delegate] cancelPendingOperations];
}
- (ODMobileMBOTaskTypesPriv*)getDownloadState
{
    return (ODMobileMBOTaskTypesPriv*)[self i_getDownloadState];
}

- (ODMobileMBOTaskTypesPriv*) getOriginalState
{
    return (ODMobileMBOTaskTypesPriv*)[self i_getOriginalState];
}
-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 70:
        return self.surrogateKey;
    default:
         return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 70:
        self.surrogateKey = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 68:
        return self.TASK_TYPE_ID;
    case 69:
        return self.EMPLOYEE_ID;
    default:
         return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 68:
        self.TASK_TYPE_ID = v;
        break;;
    case 69:
        self.EMPLOYEE_ID = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (SUPObjectList*)getLogRecords
{
   return [ODMobileLogRecordImpl findByEntity:@"MBOTaskTypesPriv":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	MBOTaskTypesPriv = \n\
	    TASK_TYPE_ID = %@,\n\
	    EMPLOYEE_ID = %@,\n\
	    pending = %i,\n\
	    pendingChange = %c,\n\
	    replayPending = %qi,\n\
	    replayFailure = %qi,\n\
	    surrogateKey = %qi,\n\
	    replayCounter = %qi,\n\
	    disableSubmit = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.TASK_TYPE_ID
    	,self.EMPLOYEE_ID
    	,self.pending
    	,self.pendingChange
    	,self.replayPending
    	,self.replayFailure
    	,self.surrogateKey
    	,self.replayCounter
    	,self.disableSubmit
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}




+ (SUPObjectList*)findAll
{
	return [self findAll:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:263] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"c\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mbotasktypespriv\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"c\" from \"odmobile_1_20_mbotasktypespriv_os\" x_os where x_os.\"c\" = x.\"c\"))))"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	SUPObjectList* values = [SUPObjectList getInstance];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOTaskTypesPriv class]];
}



+ (SUPObjectList*)findByTASK_TYPE_ID:(NSString*)tASK_TYPE_ID
{
	return [self findByTASK_TYPE_ID:tASK_TYPE_ID skip:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findByTASK_TYPE_ID:(NSString*)tASK_TYPE_ID skip:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:282] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"c\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mbotasktypespriv\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"c\" from \"odmobile_1_20_mbotasktypespriv_os\" x_os where x_os.\"c\" = x.\"c\")))) and ( x.\"a\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:tASK_TYPE_ID];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOTaskTypesPriv class]];
}



+ (SUPObjectList*)findByEMPLOYEE_ID:(NSString*)eMPLOYEE_ID
{
	return [self findByEMPLOYEE_ID:eMPLOYEE_ID skip:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findByEMPLOYEE_ID:(NSString*)eMPLOYEE_ID skip:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:282] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"c\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mbotasktypespriv\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"c\" from \"odmobile_1_20_mbotasktypespriv_os\" x_os where x_os.\"c\" = x.\"c\")))) and ( x.\"b\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:eMPLOYEE_ID];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOTaskTypesPriv class]];
}



+ (ODMobileMBOTaskTypesPriv*)findByPrimaryKey:(NSString*)tASK_TYPE_ID withEMPLOYEE_ID:(NSString*)eMPLOYEE_ID
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:304] autorelease];
	[_selectSQL appendString:@"SELECT x.\"a\",x.\"b\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"c\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mbotasktypespriv\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"c\" from \"odmobile_1_20_mbotasktypespriv_os\" x_os where x_os.\"c\" = x.\"c\")))) and ( x.\"a\" = ? AND x.\"b\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"%@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string"]];
	[dts addObject:[SUPDataType forName:@"string"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:tASK_TYPE_ID];
	[values addObject:eMPLOYEE_ID];
	
	SUPObjectList* res = (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withClass:[ODMobileMBOTaskTypesPriv class]];
	if(res && ([res size] > 0))
	{   
		ODMobileMBOTaskTypesPriv* cus = (ODMobileMBOTaskTypesPriv*)[res item:0];
	    return cus;
	}
	else
	    return nil;
}



/*!
  @method
  @abstract Generated class method 
  @throws SUPPersistenceException
 */
+ (ODMobileMBOTaskTypesPrivSynchronizationParameters*)getSynchronizationParameters
{
    return (ODMobileMBOTaskTypesPrivSynchronizationParameters*)[(SUPSyncParamEntityDelegate*)([[ODMobileODMobileDB delegate] getDelegate:@"MBOTaskTypesPrivSynchronizationParameters"]) getSynchronizationParameters];
}

/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query
{
    return [(SUPEntityDelegate*)([[self class] delegate]) getSize:query];
}

@end