/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileObjField.h"
#import "ODMobileObjFieldMetaData.h"
#import "SUPJsonObject.h"
#import "ODMobileODMobileDB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"

@implementation ODMobileObjField

@synthesize vl = _vl;
@synthesize nm = _nm;

static SUPClassDelegate *g_ODMobileObjField_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileObjField_delegate == nil) {
			g_ODMobileObjField_delegate = [[SUPClassDelegate alloc] initWithName:@"ODMobileObjField" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileObjField_delegate retain] autorelease];
}
- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
static SUPClassMetaDataRBS* ODMobileObjField_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (ODMobileObjField_META_DATA == nil) {
 	   	ODMobileObjField_META_DATA = [[ODMobileObjFieldMetaData alloc] init];
	}
	
	return ODMobileObjField_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[ODMobileObjField metaData];
        [self setClassDelegate:[[self class] delegate]];
        
    }
    return self;    
}

-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 653:
        return self.vl;
    case 654:
        return self.nm;
    default:
        return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 653:
        self.vl = v;
        break;;
    case 654:
        self.nm = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
+ (ODMobileObjField*)getInstance
{
    ODMobileObjField* me = [[ODMobileObjField alloc] init];
    [me autorelease];
    return me;
}
- (void)dealloc
{
    if(_vl)
    {
        [_vl release];
        _vl = nil;
    }
    if(_nm)
    {
        [_nm release];
        _nm = nil;
    }
	[super dealloc];
}

@end