/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileLocalKeyGenerator.h"
#import "ODMobileLocalKeyGeneratorMetaData.h"
#import "SUPLocalEntityDelegate.h"
#import "ODMobileODMobileDB.h"
#import "SUPEntityDelegate.h"
#import "SUPLocalKeyGenerator.h"

@implementation ODMobileLocalKeyGenerator

static SUPLocalEntityDelegate *g_ODMobileLocalKeyGenerator_delegate = nil;

+ (SUPLocalEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileLocalKeyGenerator_delegate == nil) {
			g_ODMobileLocalKeyGenerator_delegate = [[SUPLocalEntityDelegate alloc] initWithName:@"ODMobileLocalKeyGenerator" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileLocalKeyGenerator_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* ODMobileLocalKeyGenerator_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (ODMobileLocalKeyGenerator_META_DATA == nil) {
 	   	ODMobileLocalKeyGenerator_META_DATA = [[ODMobileLocalKeyGeneratorMetaData alloc] init];
	}
	
	return ODMobileLocalKeyGenerator_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (id)init
{
    self = [super initWithParameters:[ODMobileODMobileDB delegate]:@"co_odmobile_1_21_localkeygenerator":100000];
    if (self) {
        // Initialization code here.
        [SUPLocalKeyGenerator setObjectInstance:@"ODMobile":self];
    }
    
    return self;
}

+ (ODMobileLocalKeyGenerator*)getInstance
{
    ODMobileLocalKeyGenerator* me = [[ODMobileLocalKeyGenerator alloc] init];
    [me autorelease];
    return me;
}

+ (int64_t)generateId
{
    return [[ODMobileODMobileDB delegate] generateLocalId];
}

@end