/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileMBOActivityTemplates.h"
#import "ODMobileMBOActivityTemplatesMetaData.h"
#import "SUPJsonObject.h"
#import "ODMobileODMobileDB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "ODMobileKeyGenerator.h"
#import "ODMobileLocalKeyGenerator.h"
#import "ODMobileLogRecordImpl.h"

@implementation ODMobileMBOActivityTemplates

@synthesize ACTIVITY_TEMPLATE_ID = _ACTIVITY_TEMPLATE_ID;
@synthesize ACTIVITY_NAME = _ACTIVITY_NAME;
@synthesize TIME_PERIOD = _TIME_PERIOD;
@synthesize ACTIVITY_TYPE_ID = _ACTIVITY_TYPE_ID;
@synthesize CATEGORY_ID = _CATEGORY_ID;
@synthesize ACTIVITY_PRIORITY_ID = _ACTIVITY_PRIORITY_ID;
@synthesize BUSINESS_PROCESS_ID = _BUSINESS_PROCESS_ID;
@synthesize QUESTION_ID = _QUESTION_ID;
@synthesize ANSWER_ITEM_ID = _ANSWER_ITEM_ID;
@synthesize surrogateKey = _surrogateKey;

- (int64_t)surrogateKey
{
    return _surrogateKey;
}

- (void)setACTIVITY_TEMPLATE_ID:(NSString*)newACTIVITY_TEMPLATE_ID
{
    if (newACTIVITY_TEMPLATE_ID != self->_ACTIVITY_TEMPLATE_ID)
    {
		[self->_ACTIVITY_TEMPLATE_ID release];
        self->_ACTIVITY_TEMPLATE_ID = [newACTIVITY_TEMPLATE_ID retain];
        self.isDirty = YES;
    }
}

- (void)setACTIVITY_NAME:(NSString*)newACTIVITY_NAME
{
    if (newACTIVITY_NAME != self->_ACTIVITY_NAME)
    {
		[self->_ACTIVITY_NAME release];
        self->_ACTIVITY_NAME = [newACTIVITY_NAME retain];
        self.isDirty = YES;
    }
}

- (void)setTIME_PERIOD:(NSString*)newTIME_PERIOD
{
    if (newTIME_PERIOD != self->_TIME_PERIOD)
    {
		[self->_TIME_PERIOD release];
        self->_TIME_PERIOD = [newTIME_PERIOD retain];
        self.isDirty = YES;
    }
}

- (void)setACTIVITY_TYPE_ID:(NSString*)newACTIVITY_TYPE_ID
{
    if (newACTIVITY_TYPE_ID != self->_ACTIVITY_TYPE_ID)
    {
		[self->_ACTIVITY_TYPE_ID release];
        self->_ACTIVITY_TYPE_ID = [newACTIVITY_TYPE_ID retain];
        self.isDirty = YES;
    }
}

- (void)setCATEGORY_ID:(NSString*)newCATEGORY_ID
{
    if (newCATEGORY_ID != self->_CATEGORY_ID)
    {
		[self->_CATEGORY_ID release];
        self->_CATEGORY_ID = [newCATEGORY_ID retain];
        self.isDirty = YES;
    }
}

- (void)setACTIVITY_PRIORITY_ID:(NSString*)newACTIVITY_PRIORITY_ID
{
    if (newACTIVITY_PRIORITY_ID != self->_ACTIVITY_PRIORITY_ID)
    {
		[self->_ACTIVITY_PRIORITY_ID release];
        self->_ACTIVITY_PRIORITY_ID = [newACTIVITY_PRIORITY_ID retain];
        self.isDirty = YES;
    }
}

- (void)setBUSINESS_PROCESS_ID:(NSString*)newBUSINESS_PROCESS_ID
{
    if (newBUSINESS_PROCESS_ID != self->_BUSINESS_PROCESS_ID)
    {
		[self->_BUSINESS_PROCESS_ID release];
        self->_BUSINESS_PROCESS_ID = [newBUSINESS_PROCESS_ID retain];
        self.isDirty = YES;
    }
}

- (void)setQUESTION_ID:(NSString*)newQUESTION_ID
{
    if (newQUESTION_ID != self->_QUESTION_ID)
    {
		[self->_QUESTION_ID release];
        self->_QUESTION_ID = [newQUESTION_ID retain];
        self.isDirty = YES;
    }
}

- (void)setANSWER_ITEM_ID:(NSString*)newANSWER_ITEM_ID
{
    if (newANSWER_ITEM_ID != self->_ANSWER_ITEM_ID)
    {
		[self->_ANSWER_ITEM_ID release];
        self->_ANSWER_ITEM_ID = [newANSWER_ITEM_ID retain];
        self.isDirty = YES;
    }
}

- (void)setSurrogateKey:(int64_t)newSurrogateKey
{
    if (newSurrogateKey != self->_surrogateKey)
    {
        self->_surrogateKey = newSurrogateKey;
        self.isNew = YES;
    }
}

static SUPEntityDelegate *g_ODMobileMBOActivityTemplates_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileMBOActivityTemplates_delegate == nil) {
			g_ODMobileMBOActivityTemplates_delegate = [[SUPEntityDelegate alloc] initWithName:@"ODMobileMBOActivityTemplates" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileMBOActivityTemplates_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* ODMobileMBOActivityTemplates_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (ODMobileMBOActivityTemplates_META_DATA == nil) {
		ODMobileMBOActivityTemplates_META_DATA = [[ODMobileMBOActivityTemplatesMetaData alloc] init];
	}
	
	return ODMobileMBOActivityTemplates_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return [[self delegate] callbackHandler];
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	[[self delegate] registerCallbackHandler:newCallbackHandler];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [ODMobileMBOActivityTemplates metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[ODMobileMBOActivityTemplates delegate]];
    }
    return self;    
}

- (void)dealloc
{
    if(_ACTIVITY_TEMPLATE_ID)
    {
        [_ACTIVITY_TEMPLATE_ID release];
        _ACTIVITY_TEMPLATE_ID = nil;
    }
    if(_ACTIVITY_NAME)
    {
        [_ACTIVITY_NAME release];
        _ACTIVITY_NAME = nil;
    }
    if(_TIME_PERIOD)
    {
        [_TIME_PERIOD release];
        _TIME_PERIOD = nil;
    }
    if(_ACTIVITY_TYPE_ID)
    {
        [_ACTIVITY_TYPE_ID release];
        _ACTIVITY_TYPE_ID = nil;
    }
    if(_CATEGORY_ID)
    {
        [_CATEGORY_ID release];
        _CATEGORY_ID = nil;
    }
    if(_ACTIVITY_PRIORITY_ID)
    {
        [_ACTIVITY_PRIORITY_ID release];
        _ACTIVITY_PRIORITY_ID = nil;
    }
    if(_BUSINESS_PROCESS_ID)
    {
        [_BUSINESS_PROCESS_ID release];
        _BUSINESS_PROCESS_ID = nil;
    }
    if(_QUESTION_ID)
    {
        [_QUESTION_ID release];
        _QUESTION_ID = nil;
    }
    if(_ANSWER_ITEM_ID)
    {
        [_ANSWER_ITEM_ID release];
        _ANSWER_ITEM_ID = nil;
    }
	[super dealloc];
}


- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

+ (ODMobileMBOActivityTemplates*)find:(int64_t)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:[NSNumber numberWithLong:id_]];
    return (ODMobileMBOActivityTemplates*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

+ (SUPObjectList*)findWithQuery:(SUPQuery*)query
{
    return (SUPObjectList*)[(SUPEntityDelegate*)([[self class] delegate])  findWithQuery:query:[ODMobileMBOActivityTemplates class]];
}

- (int64_t)_pk
{
    return (int64_t)[[self i_pk] longValue];
}

+ (ODMobileMBOActivityTemplates*)load:(int64_t)id_
{
    return (ODMobileMBOActivityTemplates*)[(SUPEntityDelegate*)([[self class] delegate]) load:[NSNumber numberWithLong:id_]];
}

+ (ODMobileMBOActivityTemplates*)getInstance
{
    ODMobileMBOActivityTemplates* me = [[ODMobileMBOActivityTemplates alloc] init];
    [me autorelease];
    return me;
}
- (SUPString)getLastOperation
{
    if (self.pendingChange == 'C')
    {
        return @"create";
    }
    else if (self.pendingChange == 'D')
    {
        return @"delete";
    }
    else if (self.pendingChange == 'U')
    {
        return @"update";
    }
    return @"";

}
+ (void)submitPendingOperations
{
    [[[self class] delegate] submitPendingOperations];
}

+ (void)cancelPendingOperations
{
    [[[self class] delegate] cancelPendingOperations];
}
- (ODMobileMBOActivityTemplates*)getDownloadState
{
    return (ODMobileMBOActivityTemplates*)[self i_getDownloadState];
}

- (ODMobileMBOActivityTemplates*) getOriginalState
{
    return (ODMobileMBOActivityTemplates*)[self i_getOriginalState];
}
-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 17:
        return self.surrogateKey;
    default:
         return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 17:
        self.surrogateKey = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPString) getAttributeNullableString:(int)id_
{
    switch(id_)
    {
    case 9:
        return self.ACTIVITY_NAME;
    case 10:
        return self.TIME_PERIOD;
    case 11:
        return self.ACTIVITY_TYPE_ID;
    case 12:
        return self.CATEGORY_ID;
    case 13:
        return self.ACTIVITY_PRIORITY_ID;
    case 14:
        return self.BUSINESS_PROCESS_ID;
    case 15:
        return self.QUESTION_ID;
    case 16:
        return self.ANSWER_ITEM_ID;
    default:
         return [super getAttributeNullableString:id_];
    }
}

-(void) setAttributeNullableString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 9:
        self.ACTIVITY_NAME = v;
        break;;
    case 10:
        self.TIME_PERIOD = v;
        break;;
    case 11:
        self.ACTIVITY_TYPE_ID = v;
        break;;
    case 12:
        self.CATEGORY_ID = v;
        break;;
    case 13:
        self.ACTIVITY_PRIORITY_ID = v;
        break;;
    case 14:
        self.BUSINESS_PROCESS_ID = v;
        break;;
    case 15:
        self.QUESTION_ID = v;
        break;;
    case 16:
        self.ANSWER_ITEM_ID = v;
        break;;
    default:
        [super setAttributeNullableString:id_:v];
        break;;
    }
}
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 8:
        return self.ACTIVITY_TEMPLATE_ID;
    default:
         return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 8:
        self.ACTIVITY_TEMPLATE_ID = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (SUPObjectList*)getLogRecords
{
   return [ODMobileLogRecordImpl findByEntity:@"MBOActivityTemplates":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	MBOActivityTemplates = \n\
	    ACTIVITY_TEMPLATE_ID = %@,\n\
	    ACTIVITY_NAME = %@,\n\
	    TIME_PERIOD = %@,\n\
	    ACTIVITY_TYPE_ID = %@,\n\
	    CATEGORY_ID = %@,\n\
	    ACTIVITY_PRIORITY_ID = %@,\n\
	    BUSINESS_PROCESS_ID = %@,\n\
	    QUESTION_ID = %@,\n\
	    ANSWER_ITEM_ID = %@,\n\
	    pending = %i,\n\
	    pendingChange = %c,\n\
	    replayPending = %qi,\n\
	    replayFailure = %qi,\n\
	    surrogateKey = %qi,\n\
	    replayCounter = %qi,\n\
	    disableSubmit = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.ACTIVITY_TEMPLATE_ID
    	,self.ACTIVITY_NAME
    	,self.TIME_PERIOD
    	,self.ACTIVITY_TYPE_ID
    	,self.CATEGORY_ID
    	,self.ACTIVITY_PRIORITY_ID
    	,self.BUSINESS_PROCESS_ID
    	,self.QUESTION_ID
    	,self.ANSWER_ITEM_ID
    	,self.pending
    	,self.pendingChange
    	,self.replayPending
    	,self.replayFailure
    	,self.surrogateKey
    	,self.replayCounter
    	,self.disableSubmit
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}




+ (SUPObjectList*)findAll
{
	return [self findAll:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:336] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mboactivitytemplates\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"j\" from \"odmobile_1_20_mboactivitytemplates_os\" x_os where x_os.\"j\" "
	                               "= x.\"j\"))))"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	SUPObjectList* values = [SUPObjectList getInstance];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOActivityTemplates class]];
}



+ (ODMobileMBOActivityTemplates*)findByPrimaryKey:(NSString*)aCTIVITY_TEMPLATE_ID
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:361] autorelease];
	[_selectSQL appendString:@"SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mboactivitytemplates\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"j\" from \"odmobile_1_20_mboactivitytemplates_os\" x_os where x_o"
	                               "s.\"j\" = x.\"j\")))) and ( x.\"a\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"%@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:aCTIVITY_TEMPLATE_ID];
	
	SUPObjectList* res = (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withClass:[ODMobileMBOActivityTemplates class]];
	if(res && ([res size] > 0))
	{   
		ODMobileMBOActivityTemplates* cus = (ODMobileMBOActivityTemplates*)[res item:0];
	    return cus;
	}
	else
	    return nil;
}



+ (SUPObjectList*)getByActivityTypeId:(NSString*)aCTIVITY_TYPE_ID
{
	return [self getByActivityTypeId:aCTIVITY_TYPE_ID skip:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)getByActivityTypeId:(NSString*)aCTIVITY_TYPE_ID skip:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:358] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mboactivitytemplates\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"j\" from \"odmobile_1_20_mboactivitytemplates_os\" x_os where x_os.\"j\" "
	                               "= x.\"j\")))) and ( x.\"d\" like ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string?"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:aCTIVITY_TYPE_ID];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOActivityTemplates class]];
}



+ (SUPObjectList*)getByQuestionAndAnswerId:(NSString*)qUESTION_ID withANSWER_ITEM_ID:(NSString*)aNSWER_ITEM_ID
{
	return [self getByQuestionAndAnswerId:qUESTION_ID withANSWER_ITEM_ID:aNSWER_ITEM_ID skip:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)getByQuestionAndAnswerId:(NSString*)qUESTION_ID withANSWER_ITEM_ID:(NSString*)aNSWER_ITEM_ID skip:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:371] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mboactivitytemplates\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"j\" from \"odmobile_1_20_mboactivitytemplates_os\" x_os where x_os.\"j\" "
	                               "= x.\"j\")))) and ( x.\"h\" = ? AND x.\"i\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string?"]];
	[dts addObject:[SUPDataType forName:@"string?"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:qUESTION_ID];
	[values addObject:aNSWER_ITEM_ID];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOActivityTemplates class]];
}

/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query
{
    return [(SUPEntityDelegate*)([[self class] delegate]) getSize:query];
}

@end