/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileMBOTaskBlockMetrics.h"
#import "ODMobileMBOTaskBlockMetricsMetaData.h"
#import "SUPJsonObject.h"
#import "ODMobileODMobileDB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "ODMobileKeyGenerator.h"
#import "ODMobileLocalKeyGenerator.h"
#import "ODMobileLogRecordImpl.h"
#import "SUPSyncParamEntityDelegate.h"

@implementation ODMobileMBOTaskBlockMetrics

@synthesize TASK_ID = _TASK_ID;
@synthesize QUESTION_BLOCK_ID = _QUESTION_BLOCK_ID;
@synthesize METRIC_ID = _METRIC_ID;
@synthesize METRIC_VALUE = _METRIC_VALUE;
@synthesize EMPLOYEE_ID = _EMPLOYEE_ID;
@synthesize surrogateKey = _surrogateKey;

- (int64_t)surrogateKey
{
    return _surrogateKey;
}

- (void)setTASK_ID:(NSString*)newTASK_ID
{
    if (newTASK_ID != self->_TASK_ID)
    {
		[self->_TASK_ID release];
        self->_TASK_ID = [newTASK_ID retain];
        self.isDirty = YES;
    }
}

- (void)setQUESTION_BLOCK_ID:(NSString*)newQUESTION_BLOCK_ID
{
    if (newQUESTION_BLOCK_ID != self->_QUESTION_BLOCK_ID)
    {
		[self->_QUESTION_BLOCK_ID release];
        self->_QUESTION_BLOCK_ID = [newQUESTION_BLOCK_ID retain];
        self.isDirty = YES;
    }
}

- (void)setMETRIC_ID:(NSString*)newMETRIC_ID
{
    if (newMETRIC_ID != self->_METRIC_ID)
    {
		[self->_METRIC_ID release];
        self->_METRIC_ID = [newMETRIC_ID retain];
        self.isDirty = YES;
    }
}

- (void)setMETRIC_VALUE:(NSString*)newMETRIC_VALUE
{
    if (newMETRIC_VALUE != self->_METRIC_VALUE)
    {
		[self->_METRIC_VALUE release];
        self->_METRIC_VALUE = [newMETRIC_VALUE retain];
        self.isDirty = YES;
    }
}

- (void)setEMPLOYEE_ID:(NSString*)newEMPLOYEE_ID
{
    if (newEMPLOYEE_ID != self->_EMPLOYEE_ID)
    {
		[self->_EMPLOYEE_ID release];
        self->_EMPLOYEE_ID = [newEMPLOYEE_ID retain];
        self.isDirty = YES;
    }
}

- (void)setSurrogateKey:(int64_t)newSurrogateKey
{
    if (newSurrogateKey != self->_surrogateKey)
    {
        self->_surrogateKey = newSurrogateKey;
        self.isNew = YES;
    }
}

static SUPEntityDelegate *g_ODMobileMBOTaskBlockMetrics_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileMBOTaskBlockMetrics_delegate == nil) {
			g_ODMobileMBOTaskBlockMetrics_delegate = [[SUPEntityDelegate alloc] initWithName:@"ODMobileMBOTaskBlockMetrics" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileMBOTaskBlockMetrics_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* ODMobileMBOTaskBlockMetrics_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (ODMobileMBOTaskBlockMetrics_META_DATA == nil) {
		ODMobileMBOTaskBlockMetrics_META_DATA = [[ODMobileMBOTaskBlockMetricsMetaData alloc] init];
	}
	
	return ODMobileMBOTaskBlockMetrics_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return [[self delegate] callbackHandler];
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	[[self delegate] registerCallbackHandler:newCallbackHandler];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [ODMobileMBOTaskBlockMetrics metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[ODMobileMBOTaskBlockMetrics delegate]];
    }
    return self;    
}

- (void)dealloc
{
    if(_TASK_ID)
    {
        [_TASK_ID release];
        _TASK_ID = nil;
    }
    if(_QUESTION_BLOCK_ID)
    {
        [_QUESTION_BLOCK_ID release];
        _QUESTION_BLOCK_ID = nil;
    }
    if(_METRIC_ID)
    {
        [_METRIC_ID release];
        _METRIC_ID = nil;
    }
    if(_METRIC_VALUE)
    {
        [_METRIC_VALUE release];
        _METRIC_VALUE = nil;
    }
    if(_EMPLOYEE_ID)
    {
        [_EMPLOYEE_ID release];
        _EMPLOYEE_ID = nil;
    }
	[super dealloc];
}


- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

+ (ODMobileMBOTaskBlockMetrics*)find:(int64_t)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:[NSNumber numberWithLong:id_]];
    return (ODMobileMBOTaskBlockMetrics*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

+ (SUPObjectList*)findWithQuery:(SUPQuery*)query
{
    return (SUPObjectList*)[(SUPEntityDelegate*)([[self class] delegate])  findWithQuery:query:[ODMobileMBOTaskBlockMetrics class]];
}

- (int64_t)_pk
{
    return (int64_t)[[self i_pk] longValue];
}

+ (ODMobileMBOTaskBlockMetrics*)load:(int64_t)id_
{
    return (ODMobileMBOTaskBlockMetrics*)[(SUPEntityDelegate*)([[self class] delegate]) load:[NSNumber numberWithLong:id_]];
}

+ (ODMobileMBOTaskBlockMetrics*)getInstance
{
    ODMobileMBOTaskBlockMetrics* me = [[ODMobileMBOTaskBlockMetrics alloc] init];
    [me autorelease];
    return me;
}
- (SUPString)getLastOperation
{
    if (self.pendingChange == 'C')
    {
        return @"create";
    }
    else if (self.pendingChange == 'D')
    {
        return @"delete";
    }
    else if (self.pendingChange == 'U')
    {
        return @"update";
    }
    return @"";

}
+ (void)submitPendingOperations
{
    [[[self class] delegate] submitPendingOperations];
}

+ (void)cancelPendingOperations
{
    [[[self class] delegate] cancelPendingOperations];
}
- (ODMobileMBOTaskBlockMetrics*)getDownloadState
{
    return (ODMobileMBOTaskBlockMetrics*)[self i_getDownloadState];
}

- (ODMobileMBOTaskBlockMetrics*) getOriginalState
{
    return (ODMobileMBOTaskBlockMetrics*)[self i_getOriginalState];
}
-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 67:
        return self.surrogateKey;
    default:
         return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 67:
        self.surrogateKey = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPString) getAttributeNullableString:(int)id_
{
    switch(id_)
    {
    case 65:
        return self.METRIC_VALUE;
    default:
         return [super getAttributeNullableString:id_];
    }
}

-(void) setAttributeNullableString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 65:
        self.METRIC_VALUE = v;
        break;;
    default:
        [super setAttributeNullableString:id_:v];
        break;;
    }
}
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 62:
        return self.TASK_ID;
    case 63:
        return self.QUESTION_BLOCK_ID;
    case 64:
        return self.METRIC_ID;
    case 66:
        return self.EMPLOYEE_ID;
    default:
         return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 62:
        self.TASK_ID = v;
        break;;
    case 63:
        self.QUESTION_BLOCK_ID = v;
        break;;
    case 64:
        self.METRIC_ID = v;
        break;;
    case 66:
        self.EMPLOYEE_ID = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (SUPObjectList*)getLogRecords
{
   return [ODMobileLogRecordImpl findByEntity:@"MBOTaskBlockMetrics":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	MBOTaskBlockMetrics = \n\
	    TASK_ID = %@,\n\
	    QUESTION_BLOCK_ID = %@,\n\
	    METRIC_ID = %@,\n\
	    METRIC_VALUE = %@,\n\
	    EMPLOYEE_ID = %@,\n\
	    pending = %i,\n\
	    pendingChange = %c,\n\
	    replayPending = %qi,\n\
	    replayFailure = %qi,\n\
	    surrogateKey = %qi,\n\
	    replayCounter = %qi,\n\
	    disableSubmit = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.TASK_ID
    	,self.QUESTION_BLOCK_ID
    	,self.METRIC_ID
    	,self.METRIC_VALUE
    	,self.EMPLOYEE_ID
    	,self.pending
    	,self.pendingChange
    	,self.replayPending
    	,self.replayFailure
    	,self.surrogateKey
    	,self.replayCounter
    	,self.disableSubmit
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}




+ (SUPObjectList*)findAll
{
	return [self findAll:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:293] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"f\",x.\"_rc\",x.\"_ds\" FROM \"odmobile_1_20_mbotaskblockmetrics\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"f\" from \"odmobile_1_20_mbotaskblockmetrics_os\" x_os where x_os.\"f\" = x.\"f\"))))"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	SUPObjectList* values = [SUPObjectList getInstance];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[ODMobileMBOTaskBlockMetrics class]];
}



+ (SUPQueryResultSet*)getByTaskId:(NSString*)tASK_ID
{
	return [self getByTaskId:tASK_ID skip:0 take:INT_MAX]; 
}


	

+ (SUPQueryResultSet*)getByTaskId:(NSString*)tASK_ID skip:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:700] autorelease];
	[_selectSQL appendString:@" b.\"a\", b.\"b\", m.\"a\", m.\"b\", m.\"c\", bm.\"d\" from \"odmobile_1_20_mbotaskblockmetrics\" bm INNER JOIN \"odmobile_1_20_mbodimquestionblocks\" b ON (bm.\"b\" LIKE b.\"a\") INNER JOIN \"odmobile_1_20_mbodimmetrics\" m ON (bm.\"c\" LIKE m.\"a\") where (((b.\"_pf\" = 1 or not exists (select b"
	                               "_os.\"c\" from \"odmobile_1_20_mbodimquestionblocks_os\" b_os where b_os.\"c\" = b.\"c\"))) and ((bm.\"_pf\" = 1 or not exists (select bm_os.\"f\" from \"odmobile_1_20_mbotaskblockmetrics_os\" bm_os where bm_os.\"f\" = bm.\"f\"))) and ((m.\"_pf\" = 1 or not exists (select m_os.\"d\" from \"odmobile_1_20_mbodimmetrics_os\" "
	                               "m_os where m_os.\"d\" = m.\"d\")))) and ( bm.\"a\" LIKE ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:tASK_ID];
	
	SUPStringList *columnnames = [[[SUPStringList alloc] initWithCapacity:6] autorelease];
	[columnnames add:@"b.QUESTION_BLOCK_ID"];
	[columnnames add:@"b.QUESTION_BLOCK_NAME"];
	[columnnames add:@"m.METRIC_ID"];
	[columnnames add:@"m.METRIC_NAME"];
	[columnnames add:@"m.METRIC_KEY"];
	[columnnames add:@"bm.METRIC_VALUE"];
	
	SUPObjectList* columntypes = [[[SUPObjectList alloc] initWithCapacity:6] autorelease];
	[columntypes add:[SUPDataType forName:@"string"]];
	[columntypes add:[SUPDataType forName:@"string?"]];
	[columntypes add:[SUPDataType forName:@"string"]];
	[columntypes add:[SUPDataType forName:@"string?"]];
	[columntypes add:[SUPDataType forName:@"string?"]];
	[columntypes add:[SUPDataType forName:@"string?"]];
	
	return [[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withColumns:columnnames withColumnTypes:columntypes withSkip:skip withTake:take];
}



/*!
  @method
  @abstract Generated class method 
  @throws SUPPersistenceException
 */
+ (ODMobileMBOTaskBlockMetricsSynchronizationParameters*)getSynchronizationParameters
{
    return (ODMobileMBOTaskBlockMetricsSynchronizationParameters*)[(SUPSyncParamEntityDelegate*)([[ODMobileODMobileDB delegate] getDelegate:@"MBOTaskBlockMetricsSynchronizationParameters"]) getSynchronizationParameters];
}

/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query
{
    return [(SUPEntityDelegate*)([[self class] delegate]) getSize:query];
}

@end