/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileOfflineAuthentication.h"
#import "ODMobileOfflineAuthenticationMetaData.h"
#import "SUPJsonObject.h"
#import "ODMobileODMobileDB.h"
#import "SUPLocalEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "ODMobileKeyGenerator.h"
#import "ODMobileLocalKeyGenerator.h"
#import "ODMobileLogRecordImpl.h"

@implementation ODMobileOfflineAuthentication

@synthesize passwordHash = _passwordHash;
@synthesize user = _user;

- (NSString*)user
{
    return _user;
}

- (void)setPasswordHash:(int32_t)newPasswordHash
{
    if (newPasswordHash != self->_passwordHash)
    {
        self->_passwordHash = newPasswordHash;
        self.isDirty = YES;
    }
}

- (void)setUser:(NSString*)newUser
{
    if (newUser != self->_user)
    {
		[self->_user release];
        self->_user = [newUser retain];
        self.isNew = YES;
    }
}

static SUPLocalEntityDelegate *g_ODMobileOfflineAuthentication_delegate = nil;

+ (SUPLocalEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileOfflineAuthentication_delegate == nil) {
			g_ODMobileOfflineAuthentication_delegate = [[SUPLocalEntityDelegate alloc] initWithName:@"ODMobileOfflineAuthentication" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileOfflineAuthentication_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* ODMobileOfflineAuthentication_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (ODMobileOfflineAuthentication_META_DATA == nil) {
		ODMobileOfflineAuthentication_META_DATA = [[ODMobileOfflineAuthenticationMetaData alloc] init];
	}
	
	return ODMobileOfflineAuthentication_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [ODMobileOfflineAuthentication metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[ODMobileOfflineAuthentication delegate]];
    }
    return self;    
}

- (void)dealloc
{
    if(_user)
    {
        [_user release];
        _user = nil;
    }
	[super dealloc];
}


- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

+ (ODMobileOfflineAuthentication*)find:(NSString*)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:id_];
    return (ODMobileOfflineAuthentication*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

- (NSString*)_pk
{
    return (NSString*)[self i_pk];
}

+ (ODMobileOfflineAuthentication*)load:(NSString*)id_
{
    return (ODMobileOfflineAuthentication*)[(SUPEntityDelegate*)([[self class] delegate]) load:id_];
}

+ (ODMobileOfflineAuthentication*)getInstance
{
    ODMobileOfflineAuthentication* me = [[ODMobileOfflineAuthentication alloc] init];
    [me autorelease];
    return me;
}
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 271:
        return self.user;
    default:
         return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 271:
        self.user = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
-(SUPInt) getAttributeInt:(int)id_
{
    switch(id_)
    {
    case 272:
        return self.passwordHash;
    default:
         return [super getAttributeInt:id_];
    }
}

-(void) setAttributeInt:(int)id_:(SUPInt)v
{
    switch(id_)
    {
    case 272:
        self.passwordHash = v;
        break;;
    default:
        [super setAttributeInt:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (SUPObjectList*)getLogRecords
{
   return [ODMobileLogRecordImpl findByEntity:@"OfflineAuthentication":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	OfflineAuthentication = \n\
	    passwordHash = %i,\n\
	    user = %@,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.passwordHash
    	,self.user
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}

@end