/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "ODMobileSISSubscriptionKey.h"
#import "ODMobileSISSubscriptionKeyMetaData.h"
#import "ODMobileODMobileDB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"
@implementation ODMobileSISSubscriptionKey

static SUPClassDelegate *g_ODMobileSISSubscriptionKey_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_ODMobileSISSubscriptionKey_delegate == nil) {
			g_ODMobileSISSubscriptionKey_delegate = [[SUPClassDelegate alloc] initWithName:@"ODMobileSISSubscriptionKey" clazz:[self class]
				metaData:[self metaData] dbDelegate:[ODMobileODMobileDB delegate] database:[ODMobileODMobileDB instance]];
		}
	}
	
	return [[g_ODMobileSISSubscriptionKey_delegate retain] autorelease];
}
static SUPClassMetaDataRBS* ODMobileSISSubscriptionKey_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (ODMobileSISSubscriptionKey_META_DATA == nil) {
 	   	ODMobileSISSubscriptionKey_META_DATA = [[ODMobileSISSubscriptionKeyMetaData alloc] init];
	}
	
	return ODMobileSISSubscriptionKey_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

@end